🚇🩹 Skip py311 build since it is using rc2 version and build fails
The build error is:

editdistance/bycython.cpp:216:12: fatal error: longintrepr.h: No such file or directory
          216 |   #include "longintrepr.h"